#!/bin/bash -e
#
# Source code post-build script complementary to the application server post-build script provided by STARTX.
# This script will be executed after the building process (s2i)
# This script must be run within a STARTX builder image
#
# For more information refer to the documentation:
#  https://github.com/startxfr/docker-images
#

cat << "EOF"
|                                                                         _ 
|  _ __ ___  _   _  __ _ _ __  _ __         _____  ____ _ _ __ ___  _ __ | | ___ 
| | '_ ` _ \| | | |/ _` | '_ \| '_ \ _____ / _ \ \/ / _` | '_ ` _ \| '_ \| |/ _ \
| | | | | | | |_| | (_| | |_) | |_) |_____|  __/>  < (_| | | | | | | |_) | |  __/
| |_| |_| |_|\__, |\__,_| .__/| .__/       \___/_/\_\__,_|_| |_| |_| .__/|_|\___|
|            |___/ _    |_| _ |_|       _ _     _                  |_|           
|  _ __   ___  ___| |_     | |__  _   _(_) | __| |
| | '_ \ / _ \/ __| __|____| '_ \| | | | | |/ _` |
| | |_) | (_) \__ \ ||_____| |_) | |_| | | | (_| |
| | .__/ \___/|___/\__|    |_.__/ \__,_|_|_|\__,_|
| |_|
| 
EOF

## Execute your own post-build logic delivered by sx lib
## if you want to fail this action, exit with error code > 0
# touch $LOG_PATH/access.log
# exit 0;

## Start default php post-build logic delivered by sx lib
doPhpPostBuild
exit 0;