#!/bin/bash -e
#
# Source code pre-deploy script complementary to the application server pre-deploy script provided by STARTX.
# This script will be executed before the deployement of a new container (or pod)
# This script must be run within a STARTX builder image
#
# For more information refer to the documentation:
#  https://github.com/startxfr/docker-images
#

cat << "EOF"
|                                                                         _ 
|  _ __ ___  _   _  __ _ _ __  _ __         _____  ____ _ _ __ ___  _ __ | | ___ 
| | '_ ` _ \| | | |/ _` | '_ \| '_ \ _____ / _ \ \/ / _` | '_ ` _ \| '_ \| |/ _ \
| | | | | | | |_| | (_| | |_) | |_) |_____|  __/>  < (_| | | | | | | |_) | |  __/
| |_| |_| |_|\__, |\__,_| .__/| .__/       \___/_/\_\__,_|_| |_| |_| .__/|_|\___|
|            |___/      |_| _ |_|        _                         |_|           
|  _ __  _ __ ___        __| | ___ _ __ | | ___  _   _
| | '_ \| '__/ _ \_____ / _` |/ _ \ '_ \| |/ _ \| | | |
| | |_) | | |  __/_____| (_| |  __/ |_) | | (_) | |_| |
| | .__/|_|  \___|      \__,_|\___| .__/|_|\___/ \__, |
| |_|                             |_|            |___/
| 
EOF

## Execute your own pre-deploy logic delivered by sx lib
## if you want to fail this action, exit with error code > 0
# touch $LOG_PATH/error.log
# exit 0;

## Start default php pre-deploy logic delivered by sx lib
doPhpPreDeploy
exit 0;
