#!/bin/bash -e
#
# Source code run script. Will replace the default container entrypoint script provided by STARTX.
# This script must be run within a STARTX builder image
#
# For more information refer to the documentation:
#  https://github.com/startxfr/docker-images
#

cat << "EOF"
|                                                                         _      
|  _ __ ___  _   _  __ _ _ __  _ __         _____  ____ _ _ __ ___  _ __ | | ___ 
| | '_ ` _ \| | | |/ _` | '_ \| '_ \ _____ / _ \ \/ / _` | '_ ` _ \| '_ \| |/ _ \
| | | | | | | |_| | (_| | |_) | |_) |_____|  __/>  < (_| | | | | | | |_) | |  __/
| |_| |_| |_|\__, |\__,_| .__/| .__/       \___/_/\_\__,_|_| |_| |_| .__/|_|\___|
|            |___/      |_|   |_|       _ _           _   _        |_|
|  _ __ _   _ _ __     __ _ _ __  _ __ | (_) ___ __ _| |_(_) ___  _ __
| | '__| | | | '_ \   / _` | '_ \| '_ \| | |/ __/ _` | __| |/ _ \| '_ \
| | |  | |_| | | | | | (_| | |_) | |_) | | | (_| (_| | |_| | (_) | | | |
| |_|   \__,_|_| |_|  \__,_| .__/| .__/|_|_|\___\__,_|\__|_|\___/|_| |_|
|                          |_|   |_|
| 
EOF

## Execute your own php-fpm + apache daemon instance
# /usr/sbin/php-fpm -D
# exec /usr/sbin/httpd -D FOREGROUND > $LOG_PATH/access.log &

## Start default php-fpm + apache process delivered by sx lib
startPhpService